name: Python Site Check
on: 
  push:
    branches:
      - master
jobs:
  python-style-check:
    runs-on: [ubuntu-latest, windows]
    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set version python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.11'

      - name: Install depencies python
        run: |
          python -m pip install --upgrade
          pip install -r requirements.txt